name: Update automated data on README.md

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    name: Update recent activity

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: '10'
  
  chess:
    name: Update chess.com stats and games
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3
      - uses: Balastrong/chess-stats-action@main
        with:
          CHESS_USERNAME: 'Balastrong'